#!/usr/bin/env bash

source /etc/functions.sh
#####################################################
# Dedicated Port config generator
# Created by Vaudois for DaemonBuilder coin
# This generator will modify the main algo.conf file
# Create the new coin.algo.conf file
# And update the stratum start file
#####################################################

clear

LPORT=2768;
UPORT=9999;

# Generate random open PORT
function EPHYMERAL_PORT(){
    while true; do
        MPORT=$[$LPORT + ($RANDOM % $UPORT)];
        (echo "" >/dev/tcp/127.0.0.1/${MPORT}) >/dev/null 2>&1
        if [ $? -ne 0 ]; then
            echo $MPORT;
            return 0;
        fi
    done
}

homedir=$( getent passwd "$USER" | cut -d: -f6 )
homebin="$homedir/bin"


cd /var/stratum/config
echo
echo -e "$YELLOW addport can randomly selects an open port for the coin above port $LPORT and open the port in UFW. $COL_RESET"
echo -e "$YELLOW It will also create a new symbol.algo.conf in $RED /var/stratum/config $COL_RESET"
echo -e "$YELLOW and will create a new stratum.symbol run file in $RED $homebin. $COL_RESET"
echo

read -e -p "Do you want to choose the port for this stratum? (y/N) : " chooseport
if [[ ("$chooseport" == "y" || "$chooseport" == "Y") ]]; then
  read -e -p "Enter the desired port (Must be available) : " MPORT
  (echo "" >/dev/tcp/127.0.0.1/${MPORT}) >/dev/null 2>&1
  if [ $? -eq 0 ]; then 
    echo "Port $MPORT is already in use, please try again" ;
    exit 1 ;
  fi
  coinport=$MPORT
else
  coinport=$(EPHYMERAL_PORT)
fi 


echo
echo -e "$RED Make sure coin symbol is all UPPER case.$COL_RESET"
read -e -p "Please enter the coin SYMBOL : " coinsymbol

echo ""
echo -e "$RED Make sure algo is in the same format as in the algo config file and a valid algo in yiimp (Case matters).$COL_RESET"
read -e -p "Please enter the coin algo : " coinalgo
if [ ! -f /var/stratum/config/${coinalgo}.conf ]; then
  echo -e "$YELLOW Sorry that algo config file doesn't exist in $RED /var/stratum/config/ $YELLOW please double check and try again. $COL_RESET"
  exit 0
fi

echo ""
read -e -p "Would you like to set a minimum value for this stratum? (y/n) : " difficultyhash
if [[ ("$difficultyhash" == "y" || "$difficultyhash" == "Y" || "$difficultyhash" == "yes" || "$difficultyhash" == "YES") ]]; then
  read -e -p "Please enter a value, example: 2 (Each coin is different) : " difficultyvalue
fi


# Make the coin symbol lower case
coinsymbollower=${coinsymbol,,}

# make sure algo is lower as well since we are Here  -- THIS WILL BREAK yescryptR* algos
# coinalgo=${coinalgo,,}

# and might as well make sure the symbol is upper case
coinsymbol=${coinsymbol^^}

# Make sure the stratum.symbol config doesnt exist
if [ -f /var/stratum/config/stratum.${coinsymbollower} ]; then
  read -r -e -p "A file for ${coinsymbol} already exists. Are you sure you want to overwrite? A new port will be generated and you will need to update your ${coinsymbol}.conf blocknotify line (y/n) : " overwrite
  if [[ ("$overwrite" == "n" || "$overwrite" == "N" || "$overwrite" == "no" || "$overwrite" == "NO") ]]; then
    echo -e "$RED Exiting... $COL_RESET"
    exit 0
  fi
fi

# Prevent duplications from people running addport multiple times for the same coin...Also known as asshats...
if [ -f /var/stratum/config/$coinsymbollower.$coinalgo.conf ]; then
  if [[ ("$overwrite" == "y" || "$overwrite" == "Y" || "$overwrite" == "yes" || "$overwrite" == "YES") ]]; then
    # Insert the port in to the new symbol.algo.conf
    sed -i '/port/c\port = '${coinport}'' $coinsymbollower.$coinalgo.conf
    echo -e "$YELLOW Port updated! Remeber to update your blocknotify line!! $COL_RESET"
  fi
else
# Since this is a new symbol we are going to add it to the other conf files first.
# First we need to check if this is the first time addport has been ran
files=(*.$coinalgo.conf)
if [ -e "${files[0]}" ]; then
for r in *.$coinalgo.conf; do
  if ! grep -Fxq "exclude = ${coinsymbol}" "$r"; then
    sed -i -e '$a\
[WALLETS]\
exclude = '${coinsymbol}'' "$r"
fi
done
fi
# Copy the default algo.conf to the new symbol.algo.conf
  cp -r $coinalgo.conf $coinsymbollower.$coinalgo.conf

# Insert the port in to the new symbol.algo.conf
  sed -i '/port/c\port = '${coinport}'' $coinsymbollower.$coinalgo.conf
# If setting a difficulty value
if [[ ("$difficultyhash" == "y" || "$difficultyhash" == "Y" || "$difficultyhash" == "yes" || "$difficultyhash" == "YES") ]]; then
  # sed -i -e '/difficulty =/a\
  # difficultyhash = '${difficultyvalue}'' $coinsymbollower.$coinalgo.conf
  sed -i 's/difficulty.*/difficulty = '${difficultyvalue}'/g' $coinsymbollower.$coinalgo.conf
fi
# Insert the include in to the new symbol.algo.conf
  sed -i -e '$a\
[WALLETS]\
include = '${coinsymbol}'' $coinsymbollower.$coinalgo.conf
fi

#Again preventing asshat duplications...
if ! grep -Fxq "exclude = ${coinsymbol}" "$coinalgo.conf"; then
# Insert the exclude in to algo.conf
  sed -i -e '$a\
[WALLETS]\
exclude = '${coinsymbol}'' $coinalgo.conf
else
  echo -e "$YELLOW ${coinsymbol} is already in $coinalgo.conf, skipping... Which means you are trying to run this multiple times for the same coin. $COL_RESET"
fi

# New coin stratum start file
echo '#!/usr/bin/env bash

STRATUM_DIR=/var/stratum

stratumstart="screen -dmS __COIN__ bash $STRATUM_DIR/run.sh __COIN__.__COINALGO__"
stratumstop="screen -X -S __COIN__ quit"

startstop () {
    cmd=$1
    case $cmd in
        stop) $stratumstop ;;
        start) $stratumstart ;;
        restart)
            $stratumstop
            sleep 1
            $stratumstart
            ;;
    esac
}

case "$1" in
    start|stop|restart) 
      startstop $1 ;;
    *)
        echo "usage: $0 [start|stop|restart]"
        exit 1
esac

' > ${homebin}/stratum.${coinsymbollower}

sed -i 's/__COIN__/'$coinsymbollower'/g' ${homebin}/stratum.${coinsymbollower}
sed -i 's/__COINALGO__/'$coinalgo'/g' ${homebin}/stratum.${coinsymbollower}

sudo chmod +x ${homebin}/stratum.${coinsymbollower}



sudo ufw allow $coinport

echo
echo "Adding stratum.${coinsymbollower} to crontab for autostart at system boot."
(crontab -l 2>/dev/null; echo "@reboot sleep 10 && bash ${homebin}/stratum.${coinsymbollower} start") | crontab -
echo
echo -e "$YELLOW Starting your new stratum...$COL_RESET"
bash stratum.${coinsymbollower} start
echo -e "$YELLOW Your new stratum is$GREEN started...$YELLOW Do NOT run the start command manually...$COL_RESET"
echo
echo -e "$YELLOW To use your new stratum type,$BLUE stratum.${coinsymbollower} start|stop|restart $COL_RESET"
echo
echo -e "$YELLOW To see the stratum screen type,$MAGENTA screen -r ${coinsymbollower} $COL_RESET"
echo
echo -e "$YELLOW The assigned dedicated port for this coins stratum is :$YELLOW $coinport $COL_RESET"
echo
echo -e "$YELLOW Make sure to add this to the Dedicated Port section in your YiiMP admin panel! $COL_RESET"

cd ~
exit 0
